---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: mongodb-1
    hostname: mongodb-1.local
    image: debian:buster
    command: /sbin/init
    privileged: True
    networks:
      - name: "local"
    network_mode: "local"
    groups:
      - mongodb
  - name: mongodb-2
    hostname: mongodb-2.local
    image: debian:buster
    command: /sbin/init
    privileged: True
    networks:
      - name: "local"
    network_mode: "local"
    groups:
      - mongodb
  - name: mongodb-3
    hostname: mongodb-3.local
    image: debian:buster
    command: /sbin/init
    privileged: True
    networks:
      - name: "local"
    network_mode: "local"
    groups:
      - mongodb
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: false
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/.vault_pass.txt"
  env:
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python"
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
