---
- name: Patch OS
  yum:
    name: "*"
    state: "latest"
    exclude: "mongodb-org*"
  register: patch

- name: Reboot node
  reboot:
    reboot_timeout: "{{ reboot_timeout }}"
  when: patch.msg != "Nothing to do"
  tags:
    - reboot

- name: Start mongod service
  service:
    name: "{{ mongod_service }}"
    state: "started"

- name: Wait for mongod service to become active
  wait_for:
    port: "{{ mongod_port }}"
    delay: 10
  when: patch.msg != "Nothing to do"

- name: Ensure replicaset converges before continuing
  community.mongodb.mongodb_status:
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_user_password }}"
    replica_set: "{{ rs }}"
    poll: 99
    interval: 10
