---
- name: Add pidFilePath in mongod.conf file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/mongod.conf
    line: '  pidFilePath: /var/run/mongodb/mongod.pid'
    regexp: '^  pidFilePath:.*'
    firstmatch: yes
    insertafter: '^  fork: true'
    state: present
  register: _mongo_conf_task
  diff: yes

- name: Add PIDFile in systemd file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/mongod.service
    line: 'PIDFile=/var/run/mongodb/mongod.pid'
    regexp: '^PIDFile.*'
    firstmatch: yes
    insertbefore: '^Type='
    state: present
  register: _systemd_task
  diff: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: _systemd_task is changed

- name: Force stop mongo (forking w/o pidfile means systemd cannot restart mongod safely)
  block:
    - name: Force stop mongod
      shell: pkill -e mongod
      register: _pkill_task
    - debug:
        var: _pkill_task
  when: _mongo_conf_task is changed or _systemd_task is changed

- name: Restart mongod in docker
  block:
    - name: Restart mongod in docker
      service:
        name: mongod
        state: started
      register: _service_task
  recover:
    - name: Force stop mongod (try again)
      shell: pkill -e mongod
      register: _pkill_task
    - debug:
        var: _pkill_task
    - name: Restart mongod in docker (try again)
      service:
        name: mongod
        state: started
      until: _service_task is succeeded
      retries: 3
      delay: 5
  always:
    - name: Inspect mongod service
      command: systemctl status mongod
      register: _status_task
    - debug:
        var: _status_task
