---
- name: Add pidFilePath in mongod.conf file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/mongod.conf
    line: '  pidFilePath: /var/run/mongodb/mongod.pid'
    regexp: '^  pidFilePath:.*'
    firstmatch: yes
    insertafter: '^  fork: true'
    state: present

- name: Add PIDFile in systemd file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/mongod.service
    line: 'PIDFile=/var/run/mongodb/mongod.pid'
    regexp: '^PIDFile.*'
    firstmatch: yes
    insertbefore: '^Type='
    state: present
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd is changed

- name: Restart mongod in docker
  service:
    name: mongod
    state: started
