---
- name: Add pidFilePath in mongod.conf file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/mongod.conf
    line: '  pidFilePath: /var/run/mongodb/mongod.pid'
    regexp: '^  pidFilePath:.*'
    firstmatch: yes
    insertafter: '^  fork: true'
    state: present
  register: _mongo_conf_task
  diff: yes

- name: Add PIDFile in systemd file (missing for collection <= v1.2.1)
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/mongod.service
    line: 'PIDFile=/var/run/mongodb/mongod.pid'
    regexp: '^PIDFile.*'
    firstmatch: yes
    insertbefore: '^Type='
    state: present
  register: _systemd_task
  diff: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: _systemd_task is changed

- name: Force stop mongo (forking w/o pidfile means systemd cannot restart mongod safely)
  shell: pkill -e mongod
  when: _mongo_conf_task is changed or _systemd_task is changed

- name: Restart mongod in docker
  service:
    name: "{{ mongod_service }}"
    state: "started"
